// Don't edit this file, generated by glsl_2_header.py

#pragma once

namespace glsl {

[[maybe_unused]] constexpr auto fs = R"(
#version 330 core
uniform float color_scalar;
in vec3 fs_color;
out vec4 FragColor;

void main() {
    FragColor = vec4(fs_color * color_scalar, 1.0);
}
)";
}  // namespace glsl