// Don't edit this file, generated by glsl_2_header.py

#pragma once

namespace glsl {

[[maybe_unused]] constexpr auto basic_lighting_light_fs = R"(
#version 400

out vec4 FragColor;

void main() {
    FragColor = vec4(1.0);
})";
}  // namespace glsl