// Don't edit this file, generated by glsl_2_header.py

#pragma once

namespace glsl {

[[maybe_unused]] constexpr auto frame_buffer_fs = R"(
#version 400

out vec4 FragColor;

in vec2 TexCoords;

uniform sampler2D texture1;

void main() {
    FragColor = texture(texture1, TexCoords);
})";
}  // namespace glsl