// Don't edit this file, generated by glsl_2_header.py

#pragma once

namespace glsl {

[[maybe_unused]] constexpr auto fs = R"(
#version 400
out vec4 frag_colour;
void main() {
    frag_colour = vec4(0.2, 0.3, 0.5, 1.0);
}
)";
}  // namespace glsl